### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [celestialorb/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by unixorn** [comment]
I also suggest renaming it to something less generic - maybe celestialorb?

**Comment by celestialorb** [comment]
Sorry, must've missed the notifications for this repo. I'll work on cleaning up the repo and getting a screenshot here shortly.

**Comment by celestialorb** [comment]
@unixorn Wouldn't the repo organization (`celestialorb`) be enough to differentiate and thus eliminate the need for a less generic repo basename?

**Comment by celestialorb** [comment]
Added a screenshot.
